export const testimonialsData = [
  {
    clientName: 'Sarah Johnson',
    propertyType: 'single-family',
    neighborhood: 'Buckhead',
    numberOfProperties: 2,
    clientSince: 2019,
    rating: 5,
    quote: 'Switching to Allay was the best decision I made for my rental properties. They handle everything professionally, communicate clearly, and my properties stay rented with great tenants. I actually sleep well at night now!',
    featured: true,
    approved: true,
  },
  {
    clientName: 'Michael Chen',
    propertyType: 'condo',
    neighborhood: 'Midtown',
    numberOfProperties: 3,
    clientSince: 2020,
    rating: 5,
    quote: 'After years of managing my condos myself, Allay has been a game-changer. They filled my vacancies in under two weeks, handle maintenance efficiently, and the monthly reports are crystal clear. Worth every penny.',
    featured: true,
    approved: true,
  },
  {
    clientName: 'Jessica Williams',
    propertyType: 'townhome',
    neighborhood: 'Virginia-Highland',
    numberOfProperties: 1,
    clientSince: 2021,
    rating: 5,
    quote: 'I was nervous about hiring a property manager, but Allay exceeded all expectations. They found an excellent tenant within days, coordinate all maintenance seamlessly, and I actually make more money than when I self-managed.',
    featured: true,
    approved: true,
  },
  {
    clientName: 'David Martinez',
    propertyType: 'single-family',
    neighborhood: 'Decatur',
    numberOfProperties: 4,
    clientSince: 2018,
    rating: 5,
    quote: 'As an out-of-state investor, I needed a management company I could trust completely. Allay has managed my Atlanta properties for over five years, and I have never had a single issue. They are responsive, professional, and deliver consistent results.',
    featured: true,
    approved: true,
  },
  {
    clientName: 'Emily Rodriguez',
    propertyType: 'condo',
    neighborhood: 'Sandy Springs',
    numberOfProperties: 2,
    clientSince: 2022,
    rating: 5,
    quote: 'The transparency and communication from Allay is unmatched. I get detailed monthly reports, they respond to my questions within hours, and my properties have stayed occupied with minimal turnover. Highly recommend!',
    featured: true,
    approved: true,
  },
  {
    clientName: 'Robert Anderson',
    propertyType: 'single-family',
    neighborhood: 'Roswell',
    numberOfProperties: 3,
    clientSince: 2019,
    rating: 5,
    quote: 'I have worked with three different property management companies over the years, and Allay is by far the best. Their tenant screening process is thorough, maintenance costs are reasonable, and I have had zero rent payment issues.',
    featured: true,
    approved: true,
  },
  {
    clientName: 'Lisa Thompson',
    propertyType: 'townhome',
    neighborhood: 'Alpharetta',
    numberOfProperties: 1,
    clientSince: 2023,
    rating: 5,
    quote: 'I was skeptical about the fees initially, but Allay has proven their value ten times over. My property rented immediately at a higher price than I expected, and the tenant they found has been perfect. No regrets!',
    featured: false,
    approved: true,
  },
  {
    clientName: 'James Patterson',
    propertyType: 'single-family',
    neighborhood: 'Marietta',
    numberOfProperties: 5,
    clientSince: 2017,
    rating: 5,
    quote: 'Managing five properties myself was exhausting. Allay took over and within three months had all properties rented with quality tenants. Their maintenance network is excellent, and their accounting is flawless. This freed up my time to focus on growing my portfolio.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Amanda Lee',
    propertyType: 'condo',
    neighborhood: 'Brookhaven',
    numberOfProperties: 2,
    clientSince: 2021,
    rating: 5,
    quote: 'The 12-month rent guarantee gave me peace of mind from day one. Allay has delivered on every promise. Professional, reliable, and they truly care about maximizing my returns while maintaining my properties well.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Christopher Davis',
    propertyType: 'multi-family',
    neighborhood: 'Smyrna',
    numberOfProperties: 1,
    clientSince: 2020,
    rating: 5,
    quote: 'Managing a duplex was twice the headache. Allay handles both units expertly, keeps them rented, and coordinates all maintenance efficiently. The monthly financial reports show me exactly where my money is going. Excellent service.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Maria Gonzalez',
    propertyType: 'single-family',
    neighborhood: 'Dunwoody',
    numberOfProperties: 3,
    clientSince: 2019,
    rating: 5,
    quote: 'I appreciate how proactive Allay is with maintenance. They catch small issues before they become expensive problems. Their tenant screening is thorough, and I have never had a bad tenant in four years.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Steven Kumar',
    propertyType: 'townhome',
    neighborhood: 'Johns Creek',
    numberOfProperties: 2,
    clientSince: 2022,
    rating: 5,
    quote: 'The online portal makes everything so easy. I can see inspections, maintenance requests, financial reports - everything in one place. Allay runs like a well-oiled machine, and it shows in the results.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Karen White',
    propertyType: 'condo',
    neighborhood: 'Chamblee',
    numberOfProperties: 1,
    clientSince: 2023,
    rating: 5,
    quote: 'I live overseas and needed a management company that could handle everything independently. Allay has been perfect - professional photos, strategic pricing, thorough screening, and seamless lease renewals. I feel confident in their hands.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Brian Foster',
    propertyType: 'single-family',
    neighborhood: 'Lawrenceville',
    numberOfProperties: 4,
    clientSince: 2018,
    rating: 5,
    quote: 'The difference between my previous property manager and Allay is night and day. Faster responses, better tenants, lower maintenance costs, and detailed reporting. I have since moved all four of my properties to them.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Nicole Brown',
    propertyType: 'townhome',
    neighborhood: 'Tucker',
    numberOfProperties: 1,
    clientSince: 2021,
    rating: 5,
    quote: 'I was spending 10+ hours per month managing my rental myself. Allay took over and I got my life back. They handle tenant issues professionally, coordinate repairs efficiently, and my tenant retention has improved dramatically.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Daniel Kim',
    propertyType: 'condo',
    neighborhood: 'Peachtree City',
    numberOfProperties: 2,
    clientSince: 2020,
    rating: 5,
    quote: 'Allay is transparent about everything - costs, timelines, market conditions. No surprises, no hidden fees. They marketed my condos effectively, found great tenants quickly, and the properties have stayed rented ever since.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Rachel Adams',
    propertyType: 'single-family',
    neighborhood: 'Cumming',
    numberOfProperties: 1,
    clientSince: 2023,
    rating: 5,
    quote: 'As a first-time landlord, I needed guidance and support. Allay walked me through every step, from pricing to tenant selection to lease agreements. They made the process stress-free and profitable.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Thomas Wright',
    propertyType: 'single-family',
    neighborhood: 'Kennesaw',
    numberOfProperties: 3,
    clientSince: 2019,
    rating: 5,
    quote: 'The RE/MAX backing gives me confidence, and Allay delivers on the promise. Professional marketing, quality tenants, proactive maintenance, and excellent financial management. They have helped me grow my portfolio significantly.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Angela Patel',
    propertyType: 'condo',
    neighborhood: 'Duluth',
    numberOfProperties: 2,
    clientSince: 2021,
    rating: 5,
    quote: 'I chose Allay for their technology platform and stayed for their exceptional service. The online portal, automated rent collection, and digital maintenance tracking make everything seamless. Plus, their team is always available when I need them.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Kevin O\'Brien',
    propertyType: 'townhome',
    neighborhood: 'Suwanee',
    numberOfProperties: 1,
    clientSince: 2022,
    rating: 5,
    quote: 'After a nightmare experience with my previous property manager, Allay has been refreshingly professional. They do what they say they will do, communicate proactively, and genuinely care about my success as an investor.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Michelle Taylor',
    propertyType: 'single-family',
    neighborhood: 'Woodstock',
    numberOfProperties: 2,
    clientSince: 2020,
    rating: 5,
    quote: 'The monthly financial statements are so detailed and clear. I can see exactly where every dollar goes. Allay has helped me optimize expenses while maintaining property quality. They truly act as partners in my investment success.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'George Harris',
    propertyType: 'multi-family',
    neighborhood: 'Stone Mountain',
    numberOfProperties: 1,
    clientSince: 2019,
    rating: 5,
    quote: 'Managing a fourplex was overwhelming until Allay took over. They keep all units rented, handle multiple tenants professionally, and the property cash flows better than ever. Excellent investment management.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Samantha Moore',
    propertyType: 'condo',
    neighborhood: 'Vinings',
    numberOfProperties: 3,
    clientSince: 2018,
    rating: 5,
    quote: 'I have been with Allay since the beginning, and watching them grow has been impressive. They have maintained the same high level of service while scaling. My properties are in great hands, and the results speak for themselves.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Patrick Murphy',
    propertyType: 'single-family',
    neighborhood: 'Canton',
    numberOfProperties: 2,
    clientSince: 2021,
    rating: 5,
    quote: 'Allay found better tenants than I ever did on my own. Their screening process is thorough, and it shows - on-time rent payments, respectful of the property, and they renewed their leases without issue. This is how property management should be done.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Laura Mitchell',
    propertyType: 'townhome',
    neighborhood: 'East Cobb',
    numberOfProperties: 1,
    clientSince: 2023,
    rating: 5,
    quote: 'From the initial consultation to ongoing management, Allay has been professional, transparent, and effective. My townhome rented in less than a week, and the tenant they found is wonderful. I could not be happier with my decision.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Richard Scott',
    propertyType: 'single-family',
    neighborhood: 'Acworth',
    numberOfProperties: 4,
    clientSince: 2017,
    rating: 5,
    quote: 'I have been a real estate investor for 20 years, and Allay is hands down the best property management company I have worked with. They maximize income, minimize expenses, and handle everything with exceptional professionalism.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Jennifer Clark',
    propertyType: 'condo',
    neighborhood: 'Downtown Atlanta',
    numberOfProperties: 2,
    clientSince: 2020,
    rating: 5,
    quote: 'Downtown condo rentals can be challenging, but Allay navigates the market expertly. They price competitively, market effectively, and keep my units rented with quality tenants. Their local market knowledge is invaluable.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'William Turner',
    propertyType: 'single-family',
    neighborhood: 'Norcross',
    numberOfProperties: 1,
    clientSince: 2022,
    rating: 5,
    quote: 'I inherited a rental property and had no idea where to start. Allay educated me on the market, handled all the details, and now I have a profitable rental with zero stress. They made what seemed complicated incredibly simple.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Catherine Reed',
    propertyType: 'townhome',
    neighborhood: 'Peachtree Corners',
    numberOfProperties: 3,
    clientSince: 2019,
    rating: 5,
    quote: 'The difference in my bottom line since switching to Allay has been significant. Lower vacancy rates, better tenant quality, and reduced maintenance costs. They have truly optimized my rental business.',
    featured: false,
    approved: true,
  },
  {
    clientName: 'Andrew Collins',
    propertyType: 'single-family',
    neighborhood: 'Milton',
    numberOfProperties: 2,
    clientSince: 2021,
    rating: 5,
    quote: 'Allay\'s proactive approach to property management sets them apart. They do not wait for problems to arise - they conduct regular inspections, coordinate preventative maintenance, and keep me informed every step of the way. This is the level of service every property owner deserves.',
    featured: false,
    approved: true,
  },
]
